wagtailschedules/urls.py
from django.urls import path, include

from .views import ScheduledPagesView, publish_all_scheduled, publish_all_scheduled_confirm, publish

app_name = 'wagtailschedules'

scheduled_patterns = ([
    path("", ScheduledPagesView.as_view(), name="scheduled_pages"),
    path("<int:page_id>/publish/", publish, name='publish'),
    path("publish_all/", publish_all_scheduled, name='publish_all'),
    path("publish_all/confirm/", publish_all_scheduled_confirm, name='publish_all_confirm'),
], app_name)

urlpatterns = [
    path("scheduled/", include(scheduled_patterns)),
]

wagtailschedules/views.py
from datetime import datetime, timedelta

import django_filters
from django.conf import settings
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.utils import timezone
from django.utils.http import url_has_allowed_host_and_scheme
from django.utils.translation import gettext_lazy as _
from wagtail.admin import messages
from wagtail.admin.filters import DateRangePickerWidget, WagtailFilterSet
from wagtail.admin.views.reports.base import PageReportView
from wagtail.models import Page
from wagtail.permission_policies.pages import PagePermissionPolicy


try:
    from wagtail.models import PageRevision
except ImportError:
    from wagtail.models import Revision as PageRevision

# Possible Homepagepanel
from wagtail.admin.ui.components import Component


def get_pages_for_user(request):
    user_perms = PagePermissionPolicy()
    pages = (
        Page.objects.annotate_approved_schedule()
        .filter(_approved_schedule=True)
        .prefetch_related("content_type")
        .order_by("-first_published_at")
        & user_perms.instances_user_has_permission_for(request.user, "publish")
    )

    if getattr(settings, "WAGTAIL_I18N_ENABLED", False):
        pages = pages.select_related("locale")
    return pages


class ScheduledPagesPanel(Component):
    name = "scheduled_pages"
    template_name = "wagtailschedules/scheduled_pages.html"
    order = 200

    def get_context_data(self, parent_context):
        request = parent_context["request"]
        context = super().get_context_data(parent_context)

        user_perms = PagePermissionPolicy()
        context["pages_to_be_scheduled"] = get_pages_for_user(request)
        context["request"] = request
        context["csrf_token"] = parent_context["csrf_token"]
        return context


class ScheduledPagesReportFilterSet(WagtailFilterSet):
    go_live_at = django_filters.DateFromToRangeFilter(widget=DateRangePickerWidget)

    class Meta:
        model = Page
        fields = ["go_live_at"]


class ScheduledPagesView(PageReportView):
    template_name = "wagtailadmin/reports/scheduled_pages.html"
    title = _("Pages scheduled for publishing")
    header_icon = "time"
    list_export = PageReportView.list_export 
    filterset_class = ScheduledPagesReportFilterSet

    def get_filename(self):
        return "scheduled-pages-report-{}".format(
            datetime.today().strftime("%Y-%m-%d")
        )

    def get_queryset(self):
        user_perms = PagePermissionPolicy()

        self.queryset = get_pages_for_user(self.request)
        return super().get_queryset()

    def dispatch(self, request, *args, **kwargs):
        if not PagePermissionPolicy().instances_user_has_permission_for(request.user, "publish").exists():
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


def publish(request, page_id):
    page = get_object_or_404(Page, id=page_id).specific
    if not page.permissions_for_user(request.user).can_publish():
        raise PermissionDenied

    new_go_live_timestamp = timezone.now() - timedelta(seconds = 1)
    page.go_live_at = new_go_live_timestamp
    page.save()
     # Save revision
    revision = page.save_revision(
        user=request.user,
        log_action=True)
    revision.publish()

    messages.success(request, _("Page '{0}' has been published.").format(page.get_admin_display_title()), extra_tags='time')

     # Redirect
    redirect_to = request.POST.get('next', None)
    if redirect_to and url_has_allowed_host_and_scheme(url=redirect_to, allowed_hosts={request.get_host()}):
        return redirect(redirect_to)
    else:
        return redirect('wagtailadmin_explore', page.get_parent().id)


def publish_all_scheduled_confirm(request):

    revisions_to_publish = get_pages_for_user(request)

    return TemplateResponse(
        request,
        "wagtailschedules/publish_all_confirm.html",
        {
            "revisions_to_publish": revisions_to_publish,
        }
    )


def publish_all_scheduled(request):
    if request.method == "POST":
        new_go_live_timestamp =  timezone.now() - timedelta(seconds=1)
        revisions_to_publish = get_pages_for_user(request)
        for page in revisions_to_publish:
            page.go_live_at = new_go_live_timestamp
            page.save()
            revision = page.specific.save_revision(
                user=request.user,
                log_action=True)
            revision.publish()

        messages.success(request, _("{0} pages have been published.").format(len(revisions_to_publish)), extra_tags='time')

        # Redirect
        redirect_to = request.POST.get('next', None)
        if redirect_to and url_has_allowed_host_and_scheme(url=redirect_to, allowed_hosts={request.get_host()}):
            return redirect(redirect_to)
        else:
            return redirect('wagtailschedules:scheduled_pages')

wagtailschedules/templates/wagtailadmin/reports/listing/_list_publish.html
{% extends "wagtailadmin/reports/listing/_list_page_report.html" %}

{% load i18n wagtailadmin_tags %}

{% block extra_columns %}
    <th>{% trans 'Scheduled by' %}</th>
    <th>{% trans 'Scheduled to be published' %}</th>

{% endblock %}


{% block extra_page_data%}
    <td valign="top">
        {{ page.get_latest_revision.user }}
    </td>
    <td valign="top">
        {% page_permissions page as perms %}
        <p>
            {% with page.get_latest_revision.approved_go_live_at|date:"DATETIME_FORMAT" as locking_date %}
                {% blocktrans %}
                    <b>{{ locking_date }}</b>
                {% endblocktrans %}
            {% endwith %}
        </p>
        {% if perms.can_publish %}
            <form action="{% url 'wagtailschedules:publish' page.id %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ request.path }}">
                <button type="submit" class="button button-secondary button-small">{% trans 'Publish now' %}</button>
            </form>
        {% endif %}
    </td>
{% endblock %}

wagtailschedules/templates/wagtailadmin/reports/scheduled_pages.html
{% extends 'wagtailadmin/reports/base_page_report.html' %}
{% load i18n %}
{% block listing %}
    {% include "wagtailadmin/reports/listing/_list_publish.html" %}
{% endblock %}

{% block no_results %}
    <p>{% trans "No pages scheduled for publishing were found." %}</p>
{% endblock %}

{% block actions %}
    {% if object_list.count > 0 %}
    <div class="addbutton">
        <a href="{% url 'wagtailschedules:publish_all_confirm' %}" class="button">{% trans 'Publish all scheduled pages' %}</a>
    </div>
    {% endif %}
    {{ block.super }}
{% endblock %}

wagtailschedules/templates/wagtailschedules/_list_explore.html
{% extends "wagtailadmin/pages/listing/_list.html" %}

{% load i18n wagtailadmin_tags %}

{# Page listing include, customised for 'explore' mode #}

{% block parent_page_title %}
    {% include "wagtailadmin/pages/listing/_parent_page_title_explore.html" %}
{% endblock %}

{% block post_parent_page_headers %}
    {% include "wagtailadmin/pages/listing/_table_headers_explore.html" %}
{% endblock %}

{% block page_title %}
    {% include "wagtailadmin/pages/listing/_page_title_explore.html" %}
{% endblock %}

{% block page_navigation %}
    {% include "wagtailadmin/pages/listing/_navigation_explore.html" %}
{% endblock %}

{% block no_results %}
    {% url 'wagtailadmin_pages:add_subpage' parent_page.id as add_page_url%}
    <tr><td colspan="3" class="no-results-message"><p>{% trans "No pages have been created at this location." %}{% if parent_page and parent_page_perms.can_add_subpage %} {% blocktrans trimmed %}Why not <a href="{{ add_page_url }}">create one</a>?{% endblocktrans %}{% endif %}</p></td></tr>
{% endblock %}

wagtailschedules/templates/wagtailschedules/publish_all_confirm.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% trans "Publish all scheduled pages" %}{% endblock %}

{% block content %}
    {% trans "Publish all" as title %}
    {% trans "scheduled pages" as subtitle %}
    {% include "wagtailadmin/shared/header.html" with title=title subtitle=subtitle icon="time" %}

    <div class="nice-padding">
        <p>{% trans "Are you sure you want to publish all scheduled pages? The pages listed below will be immediately published." %}</p>
        <ul>
            {% for revision in revisions_to_publish %}
                <li>{{ revision.title }}</li>
            {% endfor %}
        <ul>
        <form action="{% url 'wagtailschedules:publish_all' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="{% trans 'Yes, publish all now' %}" class="button" />
        </form>
    </div>
{% endblock %}

wagtailschedules/templates/wagtailschedules/scheduled_pages.html
{% load i18n wagtailadmin_tags %}
{% if pages_to_be_scheduled %}
    <section class="object">
        <h2 class="title-wrapper">{% trans 'Next pages scheduled to be published' %}<a class="button button-small button-secondary" style="margin-left: 15px; margin-top: -5px;" href="{% url 'wagtailschedules:scheduled_pages' %}" title="All scheduled pages">Go to report</a></h2>
        <div class="object-layout">
            <table class="listing">
                <col />
                <col width="30%"/>
                <col width="15%"/>
                <col width="15%"/>
                <thead>{# Note: the header is visually hidden behind .title-wrapper #}
                    <tr>
                        <th class="title">{% trans "Title" %}</th>
                        <th>{% trans "Type" %}</th>
                        <th>{% trans 'Scheduled by' %}</th>
                        <th>{% trans 'Scheduled to be published' %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for page in pages_to_be_scheduled %}
                        {% page_permissions page as page_perms %}
                        <tr>
                            <td class="title" valign="top">
                                <div class="title-wrapper">
                                    {% if page_perms.can_publish %}
                                        <a href="{% url 'wagtailadmin_pages:edit' page.id %}" title="{% trans 'Edit this page' %}">{{ page.specific_deferred.get_admin_display_title }}</a>
                                    {% elif page.is_previewable %}
                                        <a href="{% url 'wagtailadmin_pages:preview_for_moderation' id %}" title="{% trans 'Preview this page' %}">{{ page.specific_deferred.get_admin_display_title }}</a>
                                    {% else %}
                                        {{ page.specific_deferred.get_admin_display_title }}
                                    {% endif %}

                                    {% i18n_enabled as show_locale_labels %}
                                    {# if show_locale_labels and page.locale_id #}
                                        {# locale_label_from_id page.locale_id as locale_label #}
                                        <span class="status-tag status-tag--label">{# locale_label #}</span>
                                    {# endif #}
                                    {% include "wagtailadmin/pages/listing/_privacy_indicator.html" with page=page %}
                                    {% include "wagtailadmin/pages/listing/_locked_indicator.html" with page=page %}
                                </div>
                                <ul class="actions">
                                    {% if page_perms.can_publish %}
                                    <form action="{% url 'wagtailschedules:publish' page.id %}" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="next" value="{{ request.path }}">
                                        <button type="submit" class="button button-secondary button-small">{% trans 'Publish now' %}</button>
                                    </form>
                                    {% endif %}
                                </ul>
                            </td>
                            <td class="type" valign="top">
                                {{ page.content_type.model_class.get_verbose_name }}
                            </td>
                            <td class="type" valign="top">
                                {{ page.get_latest_revision.user }}
                            </td>
                            <td class="type" valign="top">
                                {{ page.get_latest_revision.approved_go_live_at }}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </section>
{% endif %}